APP = phy-clk-zrf16
APPSOURCES= alpaca_i2c_utils.c si534x.c
OUTS = /home/casper/pll/zrf16/prg_si5341_phyclk
SRCS = ../alpaca_i2c_utils.c si534x.c
INCLUDES = -I../
LIBDIR =
PLATFORM = -DPLATFORM=1
OBJS =

%.o: %.c
	$(CC) ${LDFLAGS} ${BOARD_FLAG} $(INCLUDES) ${CFLAGS} -c $(APPSOURCES)

all: $(OBJS)
	$(CC) ${LDFLAGS} $(INCLUDES) $(LIBDIR) $(OBJS) $(PLATFORM) $(SRCS) -o $(OUTS)

clean:
	rm -rf $(OUTS) *.o
