APP = reset-pll
APPSOURCES= alpaca_i2c_utils.c alpaca_rfclks.c reset_rfpll.c 
OUTS = home/casper/pll/reset_pll
SRCS = ../alpaca_i2c_utils.c ../alpaca_rfclks.c reset_rfpll.c
INCLUDES = -I../
LIBDIR =
PLATFORM = -DPLATFORM=1
OBJS =

%.o: %.c
	$(CC) ${LDFLAGS} ${BOARD_FLAG} $(INCLUDES) ${CFLAGS} -c $(APPSOURCES)

all: $(OBJS)
	$(CC) ${LDFLAGS} $(INCLUDES) $(LIBDIR) $(OBJS) $(PLATFORM) $(SRCS) -o $(OUTS)

clean:
	rm -rf $(OUTS) *.o
