APP = rfsoc4x2-init-lmk-gpio
APPSOURCES= ./init_rfclk_gpio.c
OUTS = ./bin/init_rfclk_gpio
SRCS = ./init_rfclk_gpio.c
INCLUDES = -I../
LIBDIR =
OBJS =

%.o: %.c
	$(CC) ${LDFLAGS} ${BOARD_FLAG} $(INCLUDES) ${CFLAGS} -c $(APPSOURCES)

all: $(OBJS)
	$(CC) ${LDFLAGS} $(INCLUDES) $(LIBDIR) $(OBJS) $(SRCS) -o $(OUTS)

clean:
	rm -rf $(OUTS) *.o
