APP = zcu216-probe-sfp
APPSOURCES= alpaca_i2c_utils.c zcu216_probe_sfp.c
OUTS = ./bin/zcu216_probe_sfp
SRCS = ../alpaca_i2c_utils.c zcu216_probe_sfp.c
INCLUDES = -I../
LIBDIR =
PLATFORM = -DPLATFORM=0
OBJS =

%.o: %.c
	$(CC) ${LDFLAGS} ${BOARD_FLAG} $(INCLUDES) ${CFLAGS} -c $(APPSOURCES)

all: $(OBJS)
	$(CC) ${LDFLAGS} $(INCLUDES) $(LIBDIR) $(OBJS) $(PLATFORM) $(SRCS) -o $(OUTS)

clean:
	rm -rf $(OUTS) *.o
