APP = i2c-utils
APPSOURCES= alpaca_i2c_utils.c alpaca_rfclks.c alpaca_zcu111_rfclk.c
OUTS = /srv/tftpboot/nfs/zcu111/conf/home/casper/bin/prg_rfpll
SRCS = ../alpaca_i2c_utils.c ../alpaca_rfclks.c alpaca_zcu111_rfclk.c
INCLUDES = -I../
LIBDIR =
PLATFORM = -DPLATFORM=3
OBJS =

%.o: %.c
	$(CC) ${LDFLAGS} ${BOARD_FLAG} $(INCLUDES) ${CFLAGS} -c $(APPSOURCES)

all: $(OBJS)
	$(CC) ${LDFLAGS} $(INCLUDES) $(LIBDIR) $(OBJS) $(PLATFORM) $(SRCS) -o $(OUTS)

clean:
	rm -rf $(OUTS) *.o
