APP = phy-clk-zcu111
APPSOURCES= alpaca_i2c_utils.c si538x.c
OUTS = /srv/tftpboot/nfs/zcu111/conf/home/casper/bin/prg_si5382_phyclk
SRCS = ../alpaca_i2c_utils.c si538x.c
INCLUDES = -I../
LIBDIR =
PLATFORM = -DPLATFORM=3
OBJS =

%.o: %.c
	$(CC) ${LDFLAGS} ${BOARD_FLAG} $(INCLUDES) ${CFLAGS} -c $(APPSOURCES)

all: $(OBJS)
	$(CC) ${LDFLAGS} $(INCLUDES) $(LIBDIR) $(OBJS) $(PLATFORM) $(SRCS) -o $(OUTS)

clean:
	rm -rf $(OUTS) *.o
